### ISSUE TITLE
error in getSubsLabel

### ISSUE THREAD

**Issue by gbottu** [YuLab-SMU/tidytree#14]
I have a bizarre issue. I tried the following:

library(treeio)
library(ggtree)
library(phangorn)
tre <- read.tree("NA.nwk")
tipseq <- read.phyDat("NA.fas",type="AA",format="fasta")
fit <- pml(tre, tipseq, k=4)
fit <- optim.pml(fit, optNni=FALSE, optBf=T, optQ=T,
                 optInv=T, optGamma=T, optEdge=TRUE,
                 optRooted=FALSE, model = "WAG",
                 control = pml.control(trace =0))
pmltree <- as.treedata(fit)

and I get the error 👍 

error in getSubsLabel(seqs, label[pp[i]], label[i], translate, removeGap) : 
  seqA should have equal length to seqB

I use R 4.0.3. Using instead a file with only one character labels does not help. Is it that amino acid sequences are not supported ? 

[NA_nwk.txt](https://github.com/YuLab-SMU/tidytree/files/5386042/NA_nwk.txt)
[NA_withnodelabels_nwk.txt](https://github.com/YuLab-SMU/tidytree/files/5386043/NA_withnodelabels_nwk.txt)
[NA_fas.txt](https://github.com/YuLab-SMU/tidytree/files/5386045/NA_fas.txt)

**Comment by GuangchuangYu** [comment]
duplicated, <https://groups.google.com/g/bioc-ggtree/c/LjLmpxgZ3gU/m/qE65y_4VBAAJ>.
