### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by arendsee** [YuLab-SMU/tidytree#2]
`tidytree` now depends on R version 3.5, but I think the latest version of R is 3.4.3

**Comment by arendsee** [comment]
I made tiny pull request to fix the issue

**Comment by GuangchuangYu** [comment]
I will downgrade the R version dependency when the pkg was accepted. 

They just force to use R-devel when submitting pkg. 😿

**Comment by GuangchuangYu** [comment]
It seems they have some complex of what should be do or what should not be, such as R version, S4 class, etc.

Maybe I should submit my pkg to CRAN 🤔 .

**Comment by arendsee** [comment]
Yeah maybe. It is a pretty general package, not specifically bioinformatics, so maybe CRAN would be better?

**Comment by GuangchuangYu** [comment]
> What is your objection to using an S4 class here? Just make an S4 class, and we can move forward.

This is quite offensive. I will submit tidytree to CRAN.

![](https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fslides.yihui.name%2Fgif%2Fflip-table.jpg)

**Comment by arendsee** [comment]
Heh, there we go, good luck!

**Comment by GuangchuangYu** [comment]
now on CRAN, <https://cran.r-project.org/package=tidytree>.

**Comment by arendsee** [comment]
Cool! Congrats :+1:
