### ISSUE TITLE
drop.tip functionality for tbl_tree class?

### ISSUE THREAD

**Issue by nick-youngblut** [YuLab-SMU/tidytree#22]
According to the [docs](https://yulab-smu.top/treedata-book/chapter2.html), one must use `ape::drop.tip()` to remove tips. So, if one has a `tbl_tree` object, the user must `tree %>% as.phylo %>% drop.tip %>% as_tibble`, but all extra columns are removed in the process. It would be helpful if tidytree had a function to remove tips (and necessary internal nodes) directly from tbl_tree objects. 

As far as I can tell `tree_subset()` cannot reproduce the functionality of `ape::drop.tip`.

**Comment by xiangpin** [comment]
I think you want to remove tips for the `tbl_tree` which contains other external associated data? The `treeio` has provided `drop.tip` for `treedata` class, it might be safer.

**Comment by nick-youngblut** [comment]
I didn't see `drop.tip` in the `treeio` docs. Thanks for the help!
