### ISSUE TITLE
Found more than one class "phylo" in cache

### ISSUE THREAD

**Issue by INicolis** [YuLab-SMU/tidytree#48]
Hello.
As described in previous issues #10 and #47 the problem remains:
tens and tens of lines full of:
```
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by 'tidytree'
```

It's impossible to ignore as the results are nested within these lines and turning message=FALSE is not a solution as it cuts all other messages as well.

Do you have a workaround?

Thanks!

**Comment by GuangchuangYu** [comment]
1. We need to register the `phylo` class via the [setOldClass](https://www.rdocumentation.org/packages/methods/versions/3.6.2/topics/setOldClass) method.
2. The `phylo` class is also needed to be registered in other packages, e.g., `phyloseq`.
3. Then, this message started to appear.


We can do nothing about it as it is not an issue of a particular package.
