### ISSUE TITLE
Allow protein sequences in `treedata`

### ISSUE THREAD

**Issue by arendsee** [YuLab-SMU/tidytree#9]
The `treedata` objects currently require the `tip_seq` and `anc_seq` slots to be of type `DNAbin`. Would it be possible to allow them to be `AAbin` as well? Currently protein sequences are not supported.

One option would be to assign the slots the `character` type.

**Comment by GuangchuangYu** [comment]
supported, see <https://github.com/YuLab-SMU/tidytree/commit/07749f1eabf4e420e879c52921d4e20c282e8fef>.
